Integrate Mayhem
mayhemheroes/amqp091-go pull request #1
Opened 2022-10-31 02:14 UTC by 4812571

2022-10-31 02:15 UTC, 4812571 commented
I believe the commits could be better on this, but I don't know how to rewrite git history.

2022-12-23 04:01 UTC, xansec requested changes
These look a lot like OSS-Fuzz integrations? Can you explain? Btw, you can "squash" your commits to a single commit before making an MR.  Please make the requested changes.

2022-12-23 04:01 UTC, xansec commented on mayhem/Dockerfile
> +# Copyright 2020 Google Inc.
Needs a package stage and you can remove the copyright.

2022-12-23 04:01 UTC, xansec commented on mayhem/build.sh
> +#!/bin/bash -eu
No need for a script for just one line.

2023-01-24 17:52 UTC, 4812571 commented
I used OSS-Fuzz conventions for my pre-harnessed Go repositories, because it was a very reusable and modular convention in my opinion. That is why there's a copyright and a build script.

2023-01-24 20:47 UTC, xansec approved these changes
LGTM!

2023-01-24 20:47 UTC, merged